#!/bin/sh
AGV=/Developer/Tools/agvtool
PUB_DIR="${HOME}/Sites/Linkstr"
PROJECT_NAME=Linkstr

${AGV} bump -all
${AGV} tag -baseurlfortag file:///var/svn/Linkstr/tags
xcodebuild -configuration Release clean
xcodebuild -configuration Release

#!/bin/sh
VERSION=`defaults read "$PWD/build/Release/${PROJECT_NAME}.app/Contents/Info" CFBundleShortVersionString`
SHORT_VERSION=`defaults read "$PWD/build/Release/${PROJECT_NAME}.app/Contents/Info" CFBundleVersion`
VER="${VERSION}/${SHORT_VERSION}"
DATE=`date -Ru`
ZIP_FILE="${PROJECT_NAME}_${SHORT_VERSION}.zip"
ZIP="${PUB_DIR}/${ZIP_FILE}"
echo "cd build/Release"
cd "build/Release"
rm -rf "Linkstr Scripts"
svn export file:///var/svn/Linkstr/trunk/Linkstr%20Scripts
echo "/usr/bin/zip -q -r ${ZIP} ${PROJECT_NAME}.app" "Linkstr Scripts"
/usr/bin/zip -q -r "${ZIP}" "${PROJECT_NAME}.app" "Linkstr Scripts"
MD5=`md5sum ${ZIP} | awk '{print $1}'`
SIZE=`du -b ${ZIP} | awk '{print $1}'`
echo "Created: ${ZIP}: ${MD5}"
TMP=`tempfile`
cat >$TMP <<EOF
<?xml version="1.0" encoding="utf-8"?> 
<rss version="2.0" 
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"> 
  <channel> 
    <title>${PROJECT_NAME} Changelog</title> 
    <link>http://linkstr.net/changes.xml</link> 
    <description>Most recent changes with links to updates.</description> 
    <language>en</language> 
    <item> 
      <title>Version ${VER}</title> 
      <description>http://linkstr.net/Last_Changes.html</description> 
      <pubDate>${DATE}</pubDate> 
      <enclosure url="http://linkstr.net/${ZIP_FILE}"
                 sparkle:shortVersionString="${VER}"
                 sparkle:md5Sum="${MD5}"
                 length="${SIZE}"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

mv $TMP ${PUB_DIR}/changes.xml
rm -rf "${HOME}/Applications/Util/${PROJECT_NAME}.app"
mv "${PROJECT_NAME}.app" "${HOME}/Applications/Util"

cd "${PUB_DIR}"
scp ${ZIP_FILE} changes.xml linkstr.net:linkstr.net
ssh linkstr.net "cd linkstr.net; rm latest.zip; ln -s ${ZIP_FILE} latest.zip"
